import type { DriveFile, DriveFolder } from '@/types/dashboard';

export const DRIVE_FILES: DriveFile[] = [
  {
    id: 1,
    name: 'Q3_Investor_Update.pdf',
    kind: 'pdf',
    size: '4.2 MB',
    mod: '2h ago',
    owner: ['MK', 'violet'],
    status: 'indexed',
    bookmark: true,
  },
  {
    id: 2,
    name: 'Annual_Compliance.docx',
    kind: 'doc',
    size: '812 KB',
    mod: 'Yesterday',
    owner: ['AL', 'blue'],
    status: 'indexed',
  },
  {
    id: 3,
    name: 'Procurement_Forecast.xlsx',
    kind: 'xls',
    size: '1.7 MB',
    mod: 'Yesterday',
    owner: ['RS', 'green'],
    status: 'processing',
  },
  {
    id: 4,
    name: 'Brand_Guidelines_v4.pdf',
    kind: 'pdf',
    size: '12.6 MB',
    mod: '3d ago',
    owner: ['JT', 'amber'],
    status: 'indexed',
    bookmark: true,
  },
  {
    id: 5,
    name: 'Engineering_Roadmap.md',
    kind: 'md',
    size: '44 KB',
    mod: '3d ago',
    owner: ['MK', 'violet'],
    status: 'indexed',
  },
  {
    id: 6,
    name: 'Sales_Pipeline.csv',
    kind: 'csv',
    size: '388 KB',
    mod: '5d ago',
    owner: ['DV', 'teal'],
    status: 'indexed',
  },
  {
    id: 7,
    name: 'Board_Deck_Final.pptx',
    kind: 'ppt',
    size: '28.4 MB',
    mod: '1w ago',
    owner: ['MK', 'violet'],
    status: 'indexed',
  },
  {
    id: 8,
    name: 'Vendor_Contract_Draft.pdf',
    kind: 'pdf',
    size: '2.1 MB',
    mod: 'Today 9:12',
    owner: ['AL', 'blue'],
    status: 'indexed',
  },
  {
    id: 9,
    name: 'Customer_Cohort_2025.pdf',
    kind: 'pdf',
    size: '5.6 MB',
    mod: 'Sep 14',
    owner: ['DV', 'teal'],
    status: 'indexed',
  },
  {
    id: 10,
    name: 'HR_Policy_Handbook.pdf',
    kind: 'pdf',
    size: '1.1 MB',
    mod: 'Aug 22',
    owner: ['JT', 'amber'],
    status: 'indexed',
  },
];

export const DRIVE_FOLDERS: DriveFolder[] = [
  { name: 'Finance', count: 42, owner: ['MK', 'violet'], tone: 'blue' },
  { name: 'Engineering', count: 28, owner: ['RS', 'green'], tone: 'violet' },
  { name: 'Legal', count: 13, owner: ['AL', 'blue'], tone: 'amber' },
  { name: 'Marketing', count: 19, owner: ['JT', 'amber'], tone: 'pink' },
  { name: 'Operations', count: 31, owner: ['DV', 'teal'], tone: 'teal' },
  { name: 'Board Docs', count: 7, owner: ['MK', 'violet'], tone: 'red' },
];
