minimumReleaseAge: 1440
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 2592000
trustLockfile: false
blockExoticSubdeps: true

allowBuilds:
  msgpackr-extract: false
  sharp: false

minimumReleaseAgeExclude:
  - eslint-plugin-react-doctor@0.5.1
  - oxlint-plugin-react-doctor@0.5.1
  - react-doctor@0.5.1

trustPolicyExclude:
  - effect@4.0.0-beta.70
  - "@effect/platform-node-shared@4.0.0-beta.70"
  - semver@6.3.1
