import type { FileKind, Tone } from '@/types/dashboard';
import Badge from './badge';

const FILE_TYPE_MAP: Record<FileKind, { tone: Tone; label: string }> = {
  pdf: { tone: 'red', label: 'PDF' },
  doc: { tone: 'blue', label: 'DOC' },
  docx: { tone: 'blue', label: 'DOCX' },
  xls: { tone: 'green', label: 'XLS' },
  xlsx: { tone: 'green', label: 'XLSX' },
  img: { tone: 'violet', label: 'IMG' },
  ppt: { tone: 'amber', label: 'PPT' },
  txt: { tone: 'slate', label: 'TXT' },
  csv: { tone: 'teal', label: 'CSV' },
  tsv: { tone: 'teal', label: 'TSV' },
  md: { tone: 'sky', label: 'MD' },
  json: { tone: 'violet', label: 'JSON' },
  xml: { tone: 'violet', label: 'XML' },
  yaml: { tone: 'violet', label: 'YAML' },
  rtf: { tone: 'blue', label: 'RTF' },
  unknown: { tone: 'slate', label: 'FILE' },
  sql: { tone: 'indigo', label: 'SQL' },
  php: { tone: 'purple', label: 'PHP' },
  bat: { tone: 'slate', label: 'BAT' },
  png: { tone: 'pink', label: 'PNG' },
  jpg: { tone: 'pink', label: 'JPG' },
  webp: { tone: 'pink', label: 'WEBP' },
  svg: { tone: 'pink', label: 'SVG' },
  bmp: { tone: 'pink', label: 'BMP' },
  zip: { tone: 'orange', label: 'ZIP' },
  rar: { tone: 'orange', label: 'RAR' },
  '7z': { tone: 'orange', label: '7Z' },
  gzip: { tone: 'orange', label: 'GZIP' },
  bzip2: { tone: 'orange', label: 'BZIP2' },
  tar: { tone: 'orange', label: 'TAR' },
  exe: { tone: 'slate', label: 'EXE' },
  iso: { tone: 'slate', label: 'ISO' },
  mp4: { tone: 'rose', label: 'MP4' },
  webm: { tone: 'rose', label: 'WEBM' },
  mp3: { tone: 'cyan', label: 'MP3' },
  jpeg: { tone: 'pink', label: 'JPEG' },
  gif: { tone: 'pink', label: 'GIF' },
  heic: { tone: 'pink', label: 'HEIC' },
  avif: { tone: 'pink', label: 'AVIF' },
  mov: { tone: 'rose', label: 'MOV' },
  avi: { tone: 'rose', label: 'AVI' },
  mkv: { tone: 'rose', label: 'MKV' },
  wav: { tone: 'cyan', label: 'WAV' },
  aac: { tone: 'cyan', label: 'AAC' },
  flac: { tone: 'cyan', label: 'FLAC' },
  ogg: { tone: 'cyan', label: 'OGG' },
  js: { tone: 'yellow', label: 'JS' },
  ts: { tone: 'blue', label: 'TS' },
  tsx: { tone: 'blue', label: 'TSX' },
  jsx: { tone: 'blue', label: 'JSX' },
  css: { tone: 'sky', label: 'CSS' },
  scss: { tone: 'pink', label: 'SCSS' },
  html: { tone: 'orange', label: 'HTML' },
  py: { tone: 'green', label: 'PY' },
  java: { tone: 'red', label: 'JAVA' },
  c: { tone: 'slate', label: 'C' },
  cpp: { tone: 'slate', label: 'C++' },
  cs: { tone: 'violet', label: 'C#' },
  go: { tone: 'cyan', label: 'GO' },
  rs: { tone: 'orange', label: 'RUST' },
  sh: { tone: 'slate', label: 'SH' },
  apk: { tone: 'green', label: 'APK' },
  odt: { tone: 'blue', label: 'ODT' },
  ods: { tone: 'green', label: 'ODS' },
  odp: { tone: 'amber', label: 'ODP' },
};

export default function FileType({ kind }: { kind: FileKind }) {
  const c = FILE_TYPE_MAP[kind] ?? FILE_TYPE_MAP.unknown;
  return <Badge tone={c.tone}>{c.label}</Badge>;
}
